# Generated by Django 4.2.7 on 2023-12-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32, verbose_name='Авиакомпания')),
                ('term', models.CharField(max_length=50, verbose_name='Терминал')),
                ('status', models.CharField(max_length=32, verbose_name='Статус')),
                ('name', models.CharField(max_length=32, verbose_name='Направления')),
                ('time', models.TimeField(max_length=12, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Онлайн табло',
                'verbose_name_plural': 'Онлайн табло',
            },
        ),
    ]
