version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello_227
      MYSQL_DATABASE: default_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Hello_227
    ports:
      - "2206:2206"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      networkDB:
        ipv4_address: 172.18.0.4  # Фиксированный IP-адрес для MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-server
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Hello_227
    networks:
      networkDB:
        ipv4_address: 172.18.0.5  # Фиксированный IP-адрес для phpMyAdmin

  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hello_227
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-volume:/data/postgres
    networks:
      networkDB:
        ipv4_address: 172.18.0.2  # Фиксированный IP-адрес для PostgreSQL

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Hello_227
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      networkDB:
        ipv4_address: 172.18.0.3  # Фиксированный IP-адрес для pgAdmin

networks:
  networkDB:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Диапазон IP-адресов для сети

volumes:
  mysql_data:
  my-postgres-volume:
  pgadmin: