services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    build: .
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hello_227
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-volume:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Hello_227
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes:
       - pgadmin:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  my-postgres-volume:
  pgadmin: