version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello_227
      MYSQL_DATABASE: default_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Hello_227
    ports:
      - "2206:2206"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-server
    restart: always
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Hello_227

volumes:
  mysql_data: