//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerContainer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPort
    {
        public int Id { get; set; }
        public string NameApplication { get; set; }
        public string Port { get; set; }
        public string Status { get; set; }
    }
}
